name: Backend CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

env:
  IMAGE_NAME: arttyu/newsfeed
  access_key: ${{ secrets.access_key }}
  secret_key: ${{ secrets.secret_key }}
  endpoint: ${{ secrets.endpoint }}

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run backend and tests in docker-compose
        run: |
          cd backend/tests
          docker compose up --build --abort-on-container-exit --exit-code-from tests

      - name: Login to DockerHub
        if: ${{ success() }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend Image
        if: ${{ success() }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:backend

      - name: Deploy backend via SSH
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker pull arttyu/newsfeed:backend
            cd ~/edufeed/backend
            docker-compose down -v
            docker-compose rm -f || true
            docker-compose up -d
